### PR TITLE
Add cluster client

### PR DESCRIPTION
**Pull request by janfreyberg**
Add a client that implements the methods to list, configure and disable single tenanted instances.

### CODE REVIEW

**Comment by acroz** [comment]
Please go ahead and merge this.

**Comment by janfreyberg** [comment]
I'm not authorized to!

**Comment by janfreyberg** [comment]
(I don't have write access)

**Comment by acroz** [comment]
No sure why - members of the Consultancy team should have write access. Have just merged it myself for now.

**Pull request merged**
